FROM golang:1.18 as build_sales-api
ENV CGO_ENABLED 0
ARG BUILD_REF
# ARG VCS_REF

# Copy the source code into the container.
COPY . /service

# Build the service binary.
WORKDIR /service
RUN go build -ldflags "-X main.build=${BUILD_REF}"


# Run the Go Binary in Alpine.
FROM alpine:3.15
ARG BUILD_DATE
ARG BUILD_REF
# RUN addgroup -g 1000 -S sales && \
#     adduser -u 1000 -h /service -G sales -S sales
COPY --from=build_sales-api /service/service /service/service
# COPY --from=build_sales-api --chown=sales:sales /service/app/tooling/sales-admin/sales-admin /service/sales-admin
# COPY --from=build_sales-api --chown=sales:sales /service/app/services/sales-api/sales-api /service/sales-api
WORKDIR /service
# USER sales
CMD ["./service"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="service-api-container" \
      org.opencontainers.image.authors="William Kennedy <bill@ardanlabs.com>" \
      org.opencontainers.image.source="https://github.com/ardanlabs/service/app/sales-api" \
      org.opencontainers.image.revision="${BUILD_REF}" \
      org.opencontainers.image.vendor="Ardan Labs"